name: inventory_app
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Icons for iOS style
  cupertino_icons: ^1.0.8

  # HTTP client for API calls
  http: ^0.13.5

  # Drawer widget with zoom animation
  flutter_zoom_drawer: ^3.0.3

  # Chart library for Flutter
  fl_chart: ^0.50.0

  # Store simple key-value pairs persistently
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Add your assets here when ready
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

  # Fonts can be added here if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
